version: '3.3'
services:
  db:
    image: 'mysql:8'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ilona
    ports:
      - '127.0.0.1:3306:3306'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      database.host: db
      database.port: 3306
      database.db: ilona
      database.user: root
      database.password: password
      mybatis.config: mybatis-configuration.xml
    depends_on:
      - db
