package uni.miskolc.ips.ilona.measurement.model.position;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

/**
 * Represent a part of a building. Rooms shall be represented by Zone objects.
 *
 * @author zsolt
 */
@Getter
@Setter
@EqualsAndHashCode
public class Zone {

    public static final Zone UNKNOWN_POSITION;

    static {
        UNKNOWN_POSITION = new Zone("Unknown");
        UNKNOWN_POSITION.setId(new UUID(0, 0));
    }

    /**
     * It is the identifier of the zone. It is generated by the system.
     */
    private UUID id;

    @EqualsAndHashCode.Exclude
    private String name;

    public Zone() {
    }

    public Zone(String name) {
        super();
        this.id = UUID.randomUUID();
        this.name = name;
    }

    @Override
    public String toString() {
        return "Zone [id=" + id + ", name=" + name + "]";
    }
}
